export const Card1 = [
  {
    id: 0,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 1,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 2,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 3,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },

  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
];
export const Card2 = [
  {
    id: 0,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 1,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 2,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 3,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },

  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
  {
    id: 4,
    price: "$150",
    Social: "Instagram",
    spon: "Instagram post",
    idName: "@softepedia",
    Follower: "20k Follower",
    user: "Samantha Nichol",
  },
];

export const threeCards = [
  {
    id: 0,
    Cover: "",
    BorderColor: "#FFC6D6",
    platform: "Instagram-Reels",
  },
  {
    id: 1,
    Cover: "",
    BorderColor: "#CDABF8",
    platform: "Facebook",
  },
  {
    id: 2,
    Cover: "",
    BorderColor: "#B9B9B9",
    platform: "Tiktok",
  },
];
export const influencerdata = [
  {
    id: 0,
    title: "Creative Full produced video by",
    userName: "@Mobyink",
    description:
      "I’ll create a full produced video as seen in the work on my instagramaccount @mobyink_ I’ll create a full produced video as seen in the work on my instagramaccount @mobyink_",
  },
];
// export const influencerImage = [
//   {
//     id: 0,
//     cover: "C:UsersjonwaOneDriveDesktopFalloverFalloverssrcassetsimg1.png",
//   },
// ];

export const data3 = [
  {
    id: 1,
    name: "kapil",
    Status: "Active",
    StatusG1: "Connected",
    color: "#008000",
    Find: "26 M",
    Pack: "Custom",
    Due: "30",
    Invest: "$20,000",
    last: "20/05/2020 - 11am",
    proposal: "Kapil Thakkar ",
    content: "Kapil Thakkar",
    date: "30-12-2023",
    detail: "Changes in Campaign Br",
    invoice: "#70707gh60",
  },
  {
    id: 2,
    name: "Gouttam",
    Status: "Active",
    StatusG1: "Connected",
    color: "#008000",
    Find: "26 M",
    Pack: "Custom",
    Due: "30",
    Invest: "$20,000",
    last: "20/05/2020 - 11am",
    proposal: "Kapil Thakkar ",
    content: "Kapil Thakkar",
    date: "30-12-2023",
    detail: "Changes in Campaign Br",
    invoice: "#70707gh60",
  },
  {
    id: 3,
    name: "jatin",
    Status: "Active",
    StatusG1: "Connected",
    StatusB: "In-Progress",
    color: "#008000",
    Find: "26 M",
    Pack: "Custom",
    Due: "30",
    Invest: "$20,000",
    last: "20/05/2020 - 11am",
    proposal: "Kapil Thakkar ",
    content: "Kapil Thakkar",
    date: "30-12-2023",
    detail: "Changes in Campaign Br",
    invoice: "#70707gh60",
  },
  {
    id: 4,
    name: "mohit",
    Status: "Active",
    StatusR: "Not-close",
    StatusB: "In-Progress",
    color: "#008000",
    Find: "26 M",
    Pack: "Custom",
    Due: "30",
    Invest: "$20,000",
    last: "20/05/2020 - 11am",
    proposal: "Kapil Thakkar ",
    content: "Kapil Thakkar",
    date: "30-12-2023",
    detail: "Changes in Campaign Br",
    invoice: "#70707gh60",
  },
  {
    id: 5,
    name: "vikas",
    Status: "Active",
    StatusB: "In-Progress",
    color: "#008000",
    Find: "26 M",
    Pack: "Custom",
    Due: "30",
    Invest: "$20,000",
    last: "20/05/2020 - 11am",
    proposal: "Kapil Thakkar ",
    content: "Kapil Thakkar",
    date: "30-12-2023",
    detail: "Changes in Campaign Br",
    invoice: "#70707gh60",
  },
];
